### ISSUE TITLE
Ability to disable "No" responses

### ISSUE THREAD

**Issue by lordmorgul** [js8call/js8call#62]
QUERY MSGS is a useful feature, but receiving No responses is not particularly useful to some user base. If the purpose is seeing who is hearing, SNR is appropriate. But receiving a No response to query msg simply adds band noise that provides little value, and specifically, for users where intent is to receive as much js8 traffic as possible without unnecessary interruptions to transmit but which still want to be responsive to direct messages.
Recommend option of turning off response "No".

**Comment by Chris-AC9KH** [comment]
> QUERY MSGS is a useful feature, but receiving No responses is not particularly useful to some user base. If the purpose is seeing who is hearing, SNR is appropriate. But receiving a No response to a group query msg simply adds band noise that provides little value

I think we're going to have to agree to disagree on this. If a QUERY MSGS is sent to ALLCALL you won't get NO responses. If it is sent to a groupcall I **expect** NO responses from stations in the group that don't have a MSG queued to give me a list of who received my query. If I query a specific station I also **expect** a NO response if they have nothing in the queue.

If we put in an option to turn off NO responses to QUERY MSGS it breaks one of the fundamental strongpoints of messaging in JS8Call.

Maybe @jsherer can comment on this, but being a long-time JS8Call user that does a lot of messaging, I depend on that feature when querying both callgroups and individual stations.

**Comment by lordmorgul** [comment]
I would not want to break group queries always... I would want to be able to prevent group auto responses only at desired times, but be able to walk away and still have direct auto responses work. So just turning off all auto reply is not a great answer even though it guarantees reception because it also breaks message relays.

The suggestions in #22 overall meet my intent if it is also able to include all group responses when turned on. I 100% agree that HB is the primary problem, while receiving, but group SNR? and MSGS queries also cause issues. Not every station needs to have this, would recommend it be option and not default. But stations wanting to primarily act as a message traffic collector have only one option now and that is turn off auto replies making them not useful for relay until manually enabled again.

It would be even more useful if able to enable/disable by API for time or day, net or while remote.

**Comment by lordmorgul** [comment]
Per my added comments there its almost a covered use case I think, and still better than it was so agree you'd want to push that forward. My comment there shows where this has one additional element of concern (a long commstat group message has no ACK to use as a reenable trigger for auto reolies).

**Comment by Chris-AC9KH** [comment]
The original PR for HB ACK's is merged to master. So work can continue on this issue. If any further comments, please leave them here.

**Comment by Chris-AC9KH** [comment]
I hate to go down the road of completely disabling a function that is set in the UI by the end user, and then turning it back on based on some arbitrary value. It violates programming ethics when a programmer takes control of a setting explicitly made in the UI by the end user.

If I do it like I did with HB ACK's where it doesn't auto-reply when it shouldn't because it breaks another feature, then it can be consider a bug fix. I only added the change to the Mode and Repeat buttons with that one to make the UI consistent since it does the same thing if a callsign is selected. But there is no instance in the code where Auto is turned off except by the watchdog timer. I think we need to leave that one well alone. I prefer the surgical approach where you identify problems in the code and fix those vs using the Big Switch and turning things on and off that shouldn't be and then telling the watchdog timer "well, just deal with it". Those instances are already there for AllCall without turning Auto off, just need to add another condition to them that was skipped over in the original design.

**Comment by Joe-K0OG** [comment]
Chris, I think you are missing my point.  *Whatever* is needed to prevent *any* directed message from being interrupted by my station responding to a query from another station or group I'm a member of -- do that which is needed, whatever you may want to call it.  If it's to disable ACKs to any query, disable responses to SNR?, GRID?, and MSG queries, etc.  Do it.  It just seemed like an easy way to accomplish that is to disable all autoresponses momentarily, rather than writing code for each individual automatic reply, but maybe I'm wrong about that.  

I'm wondering if there is objection to *preventing interruption* of reception of a directed message.  It seems that ought to be highest priority over all else.

73,
-Joe-
K0OG

**Comment by Chris-AC9KH** [comment]
@lordmorgul I fixed your concerns this morning. I did not add a boolean switch to the UI to turn off "NO" responses to a group `QUERY MSGS` as I think that is a feature that is working as-designed. If we start adding switches for every little thing the auto-reply system can send, it will make the UI cluttered, hard to understand, easy to misconfigure.

But I did prevent any unwanted auto-replies that will break incoming MSG's in all cases, not just HB ACK's, yet still allow your station to send a proper ACK when the EOT character is generated.

I consider this a bug fix, not a feature. All I did was fix instances where the auto-reply system is breaking another feature (receiving an incoming MSG) due to some oversights in the original design that consider those auto-replies to be higher priority than receiving a MSG. I did NOT queue these for later transmission. Why? Because in my experience a lot of incoming MSG's can take 5 minutes or more. If it's a weak signal situation where Slow mode is being used it can take much longer than that. It's a moot point by then - the original sender of the request that generates an auto-reply has already moved on and not paying attention anyway. If you think it's important to reply, you can manually generate your reply to their request after you receive your MSG and your station sends its ACK.

At present the dev branch I did this on is only stored on my local repo, as it will have to be rebased on master several times if backlogged PR's ever get merged, and before I can prepare a PR for it. So you can close this issue if you want - it is addressed. Just need to play the rebase game to get it into master as backlogged PR's catch up.

As a side note, if you run a Mac this fix will be available immediately in the 2.3.2-rc6 build in the releases on my GitHub repo (not doing builds for other platforms at present for pre-release testing).

**Comment by lordmorgul** [comment]
I appreciate that fix intent and think that it is a wonderful fix. The issue remains though that the only way to prevent an autoreply broken incoming traffic is to make it a MSG.

Commstat does not currently send its group broadcast traffic status as a MSG. Neither does js8spotter. That would cause alot of undesirable auto ACK. Commstat intends to have async status reception that could be multiple senders at the same time and later an async manual action ACK. This prevents there being loss of other messages that do not start and end at the same time.

**Comment by lordmorgul** [comment]
built 2.3.2-rc and testing whether any other improvement needed

**Comment by lordmorgul** [comment]
Closing for now, until more specific fix needed
I've run multiple copies of 2.3.2-rc JS8 for 2 weeks without seeing any clear signs of lost traffic (even not directed to me) due to an autoreply jumping in the middle of a decoding message. It may still be possible in higher traffic events, but not observed yet.  I believe those changes have made a big improvement in handling high traffic events. Thanks.

**Comment by Chris-AC9KH** [comment]
I've been running 2.3.2-rc6 as well for the last couple weeks and haven't had any issues yet. So I'll put in a PR on master with that change and reference this issue.

Thanks!
